# Generated by Django 2.2.7 on 2019-11-15 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0014_resident_resident_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBADAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no_badac', models.CharField(max_length=25)),
                ('case_type_badac', models.CharField(max_length=30)),
                ('complainant_badac', models.CharField(max_length=30)),
                ('case_status_badac', models.CharField(default='CFA', max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('convict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
    ]
