# Generated by Django 2.2.5 on 2019-11-15 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_resident_is_fresh_grad'),
        ('badac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBADAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no_badac', models.CharField(max_length=14)),
                ('case_type_badac', models.CharField(max_length=30)),
                ('complainant_badac', models.CharField(max_length=30)),
                ('case_status_badac', models.CharField(default='CFA', max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('convict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
        migrations.DeleteModel(
            name='badac',
        ),
    ]
