# Generated by Django 2.2.7 on 2019-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badac', '0002_auto_20191115_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbadac',
            name='case_no_badac',
            field=models.CharField(max_length=25),
        ),
    ]
