# Generated by Django 2.2.5 on 2019-11-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badac', '0003_auto_20191115_1329'),
        ('badac', '0003_auto_20191115_1520'),
    ]

    operations = [
    ]
