# Generated by Django 2.2.5 on 2019-11-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badac', '0004_merge_20191115_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbadac',
            name='case_status_badac',
            field=models.CharField(default='Red', max_length=8),
        ),
    ]
