# Generated by Django 2.2.7 on 2019-11-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('vawc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vawc',
            name='resident_case',
        ),
        migrations.AddField(
            model_name='vawc',
            name='convict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='residents.Resident'),
        ),
        migrations.AlterField(
            model_name='vawc',
            name='complainant',
            field=models.CharField(max_length=30),
        ),
    ]
