# Generated by Django 2.2.7 on 2019-11-08 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('year_level', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('father_address', models.TextField()),
                ('father_age', models.PositiveIntegerField()),
                ('father_occupation', models.CharField(max_length=30)),
                ('father_mobile', models.CharField(max_length=11)),
                ('father_precint', models.CharField(max_length=30)),
                ('father_salary', models.PositiveIntegerField()),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_address', models.TextField()),
                ('mother_age', models.PositiveIntegerField()),
                ('mother_occupation', models.CharField(max_length=30)),
                ('mother_mobile', models.CharField(max_length=11)),
                ('mother_precint', models.CharField(max_length=30)),
                ('mother_salary', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 11, 8, 14, 1, 11, 688079, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('interment_address', models.TextField()),
                ('interment_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('relationship', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 11, 8, 14, 1, 11, 688079, tzinfo=utc))),
                ('corpse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
    ]
