# Generated by Django 2.2.7 on 2019-11-11 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_auto_20191112_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 21, 24, 53, 83958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 21, 24, 53, 82957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='residents.Resident'),
        ),
    ]
