# Generated by Django 2.2.5 on 2019-11-13 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0008_auto_20191112_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
