# Generated by Django 2.2.7 on 2019-11-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0009_auto_20191113_2121'),
        ('assistance', '0009_auto_20191113_2040'),
    ]

    operations = [
    ]
