# Generated by Django 2.2.5 on 2019-11-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0010_auto_20191113_2212'),
        ('assistance', '0010_merge_20191113_2334'),
    ]

    operations = [
    ]
