# Generated by Django 2.2.5 on 2019-11-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0011_merge_20191115_1045'),
        ('assistance', '0011_merge_20191114_2325'),
    ]

    operations = [
    ]
