# Generated by Django 2.2.5 on 2019-11-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0002_auto_20191108_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_id', models.CharField(max_length=8)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='residents.Resident')),
            ],
        ),
    ]
