# Generated by Django 2.2.5 on 2019-11-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Senior',
        ),
    ]
