# Generated by Django 2.2.5 on 2019-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=14)),
                ('case_type', models.CharField(max_length=30)),
                ('complainant', models.CharField(max_length=50)),
                ('case_status', models.CharField(max_length=8)),
            ],
        ),
    ]
