# Generated by Django 2.2.5 on 2019-10-11 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katarungan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katarungan',
            name='complainant',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_complainant', message='Complainant must not contain numbers or special characters', regex='^[a-zA-Z]*$')]),
        ),
    ]
