# Generated by Django 2.2.5 on 2019-10-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_auto_20191009_2239'),
        ('katarungan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='resident_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
