# Generated by Django 2.2.5 on 2019-10-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('katarungan', '0002_auto_20191011_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katarungan',
            name='resident_case',
        ),
        migrations.AddField(
            model_name='katarungan',
            name='c_resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='residents.Resident'),
        ),
        migrations.AlterField(
            model_name='katarungan',
            name='complainant',
            field=models.CharField(max_length=30),
        ),
    ]
