# Generated by Django 2.2.7 on 2019-11-11 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('katarungan', '0004_auto_20191108_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='katarungan',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='katarungan',
            name='convict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
