# Generated by Django 2.2.7 on 2019-11-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katarungan', '0005_auto_20191112_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katarungan',
            name='case_status',
            field=models.CharField(default='CFA', max_length=8),
        ),
    ]
