# Generated by Django 2.2.5 on 2019-11-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katarungan', '0007_auto_20191113_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katarungan',
            name='convict',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convicted', to='residents.Resident'),
        ),
    ]
