# Generated by Django 2.2.5 on 2019-11-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katarungan', '0009_auto_20191113_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katarungan',
            name='case_type',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Revolt', 'Revolt'), ('Border', 'Border'), ('War', 'War'), ('Kidnapping', 'Kidnapping'), ('Hijacking', 'Hijacking'), ('Hostage', 'Hostage'), ('Attacks', 'Attacks')], max_length=30),
        ),
    ]
