# Generated by Django 2.2.5 on 2019-11-14 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0014_resident_resident_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=80)),
                ('project_details', models.TextField()),
                ('project_picture', models.ImageField(default='default.jpg', upload_to='sk_project_pics')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
    ]
