# Generated by Django 2.2.5 on 2019-11-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0014_resident_resident_profile'),
        ('sk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sk',
            new_name='Project',
        ),
    ]
