# Generated by Django 2.2.5 on 2019-10-10 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bpso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=14)),
                ('case_type', models.CharField(max_length=30)),
                ('complainant', models.CharField(max_length=50)),
                ('case_status', models.CharField(max_length=8)),
                ('resident_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
    ]
