# Generated by Django 2.2.5 on 2019-11-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpso', '0002_auto_20191115_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbpso',
            name='Select_Case_bpso',
        ),
    ]
