# Generated by Django 2.2.4 on 2019-11-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpso', '0003_remove_formbpso_select_case_bpso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbpso',
            name='case_type_bpso',
            field=models.CharField(choices=[('Disturbance', 'Disturbance'), ('Revolt', 'Revolt'), ('Border', 'Border'), ('War', 'War'), ('Kidnapping', 'Kidnapping'), ('Hijacking', 'Hijacking'), ('Hostage', 'Hostage'), ('Attacks', 'Attacks')], max_length=30),
        ),
    ]
