# Generated by Django 2.2.5 on 2019-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('civil_status', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=11)),
                ('nationality', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=60, unique=True)),
                ('religion', models.CharField(max_length=30)),
            ],
        ),
    ]
