# Generated by Django 2.2.5 on 2019-10-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('suffix', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('civil_status', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=11)),
                ('nationality', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=60, unique=True)),
                ('religion', models.CharField(max_length=30)),
                ('citizen_id', models.IntegerField()),
                ('pwd_no', models.IntegerField()),
                ('is_senior', models.BooleanField(default=False)),
                ('is_fresh_grad', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=90)),
                ('father_age', models.IntegerField()),
                ('father_address', models.CharField(max_length=100)),
                ('father_salary', models.FloatField()),
                ('father_precint', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=90)),
                ('mother_age', models.IntegerField()),
                ('mother_address', models.CharField(max_length=100)),
                ('mother_salary', models.FloatField()),
                ('mother_precint', models.CharField(max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=20)),
                ('case_remarks', models.CharField(max_length=20)),
                ('case_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
    ]
