# Generated by Django 2.2.5 on 2019-10-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolcredentials',
            name='student',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='age',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='height',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='is_fresh_grad',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='is_pwd',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='is_senior',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='pwd_no',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='weight',
        ),
        migrations.DeleteModel(
            name='CaseRecord',
        ),
        migrations.DeleteModel(
            name='SchoolCredentials',
        ),
    ]
