# Generated by Django 2.2.5 on 2019-10-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20191009_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='burialForm',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='businessPermit',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='clearanceForm',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='idForm',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='scholarshipForm',
        ),
    ]
