# Generated by Django 2.2.5 on 2019-11-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20191108_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='age',
        ),
    ]
