# Generated by Django 2.2.7 on 2019-11-12 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_resident_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
