# Generated by Django 2.2.5 on 2019-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_auto_20191112_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='is_senior',
            field=models.CharField(max_length=10),
        ),
    ]
