# Generated by Django 2.2.5 on 2019-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_auto_20191113_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='senior_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
