# Generated by Django 2.2.5 on 2019-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_auto_20191113_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='disability',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='is_pwd',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
