# Generated by Django 2.2.5 on 2019-11-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_auto_20191113_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='pwd_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
