# Generated by Django 2.2.5 on 2019-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0012_auto_20191113_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_fresh_grad',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
