# Generated by Django 2.2.5 on 2019-11-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0013_resident_is_fresh_grad'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='resident_profile',
            field=models.ImageField(default='default_profile.jpg', upload_to='resident_profile_pics'),
        ),
    ]
