# Generated by Django 2.2.5 on 2019-10-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_auto_20191009_2239'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burialform',
            name='resident_burial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='resident_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='resident_clearance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AddField(
            model_name='idform',
            name='resident_idform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AddField(
            model_name='indigencyform',
            name='resident_indigency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AddField(
            model_name='scholarshipform',
            name='resident_scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
