# Generated by Django 2.2.7 on 2019-11-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipform',
            name='resident_scholarship',
        ),
        migrations.DeleteModel(
            name='BurialForm',
        ),
        migrations.DeleteModel(
            name='ScholarshipForm',
        ),
    ]
