# Generated by Django 2.2.4 on 2019-11-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20191110_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceform',
            name='resident_clearance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AlterField(
            model_name='indigencyform',
            name='resident_indigency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
        migrations.AlterField(
            model_name='scholarshipform',
            name='resident_scholarship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
