# Generated by Django 2.2.7 on 2019-11-15 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20191115_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Email must be Valid!', regex='^[a-zA-Z0-9]*$')], verbose_name='email'),
        ),
    ]
