# Generated by Django 2.2.7 on 2019-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20191115_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='user_pics'),
        ),
    ]
